//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiidWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankTransaction
    {
        public int ID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public int EndUserID { get; set; }
        public string Description { get; set; }
        public Nullable<int> TransactionTypeID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string UpdatedByUserName { get; set; }
        public string DepositorName { get; set; }
        public Nullable<decimal> AdminFee { get; set; }
        public string Reference { get; set; }
        public Nullable<decimal> ActualAmount { get; set; }
        public string Note { get; set; }
    
        public virtual EndUser EndUser { get; set; }
        public virtual Status Status { get; set; }
    }
}
