//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiidWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceLogin
    {
        public int ID { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public Nullable<int> LogInTypeID { get; set; }
        public Nullable<System.DateTime> LogTime { get; set; }
        public Nullable<int> ShiftNo { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
