//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiidWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public Device()
        {
            this.DeviceLogins = new HashSet<DeviceLogin>();
            this.POSTransactions = new HashSet<POSTransaction>();
            this.Staffs = new HashSet<Staff>();
        }
    
        public int ID { get; set; }
        public string DeviceCode { get; set; }
        public string DeviceAppCode { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> DateTimeAdded { get; set; }
        public string Description { get; set; }
        public Nullable<int> CurrentVendorID { get; set; }
        public Nullable<int> CurrentEventID { get; set; }
        public Nullable<System.DateTime> DateTimeUpdated { get; set; }
    
        public virtual ICollection<DeviceLogin> DeviceLogins { get; set; }
        public virtual ICollection<POSTransaction> POSTransactions { get; set; }
        public virtual ICollection<Staff> Staffs { get; set; }
    }
}
