//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiidWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class EndUser
    {
        public EndUser()
        {
            this.BankTransactions = new HashSet<BankTransaction>();
            this.Friends = new HashSet<Friend>();
            this.Friends1 = new HashSet<Friend>();
            this.MyMoneys = new HashSet<MyMoney>();
            this.NewsFeeds = new HashSet<NewsFeed>();
            this.NewsFeedComments = new HashSet<NewsFeedComment>();
            this.NFCTags = new HashSet<NFCTag>();
            this.ParentChilds = new HashSet<ParentChild>();
            this.ParentChilds1 = new HashSet<ParentChild>();
            this.POSTransactions = new HashSet<POSTransaction>();
            this.PrivateMessages = new HashSet<PrivateMessage>();
            this.PrivateMessages1 = new HashSet<PrivateMessage>();
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int ID { get; set; }
        public string Surname { get; set; }
        public string Firstname { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> AccountTypeID { get; set; }
        public string IDNumber { get; set; }
        public Nullable<int> Age { get; set; }
        public string Sex { get; set; }
        public Nullable<int> RaceID { get; set; }
        public string StreetAddress { get; set; }
        public string Suburb { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string Telephone { get; set; }
        public string Cell { get; set; }
        public string Email { get; set; }
        public int StatusID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> AccountBalance { get; set; }
        public Nullable<bool> IsChildUser { get; set; }
        public string NextOfKin { get; set; }
        public string NextOfKinTelephone { get; set; }
        public string Medication { get; set; }
        public string MedicalAidCompany { get; set; }
        public string MedicalAidNumber { get; set; }
        public string Allergies { get; set; }
        public string KnownConditions { get; set; }
        public string AspNetUserID { get; set; }
        public string ProfilePicURL { get; set; }
        public Nullable<System.Guid> EmailVerificationGuid { get; set; }
        public Nullable<bool> EmailVerified { get; set; }
        public string Province { get; set; }
        public Nullable<bool> TermsAndConditionsAccepted { get; set; }
        public Nullable<bool> NewsletterAccepted { get; set; }
        public Nullable<System.DateTime> DateTimeUpdated { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Country { get; set; }
        public string Bank { get; set; }
        public string BranchCode { get; set; }
        public string AccountNumber { get; set; }
        public string AccountTypeName { get; set; }
        public string AccountHolderName { get; set; }
        public string Notes { get; set; }
        public Nullable<int> SubdomainID { get; set; }
        public Nullable<int> ParentUserID { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual ICollection<BankTransaction> BankTransactions { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<Friend> Friends { get; set; }
        public virtual ICollection<Friend> Friends1 { get; set; }
        public virtual ICollection<MyMoney> MyMoneys { get; set; }
        public virtual ICollection<NewsFeed> NewsFeeds { get; set; }
        public virtual ICollection<NewsFeedComment> NewsFeedComments { get; set; }
        public virtual ICollection<NFCTag> NFCTags { get; set; }
        public virtual ICollection<ParentChild> ParentChilds { get; set; }
        public virtual ICollection<ParentChild> ParentChilds1 { get; set; }
        public virtual ICollection<POSTransaction> POSTransactions { get; set; }
        public virtual ICollection<PrivateMessage> PrivateMessages { get; set; }
        public virtual ICollection<PrivateMessage> PrivateMessages1 { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
