//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiidWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.EventImages = new HashSet<EventImage>();
            this.Incidents = new HashSet<Incident>();
            this.Promotions = new HashSet<Promotion>();
            this.Staffs = new HashSet<Staff>();
            this.TicketClasses = new HashSet<TicketClass>();
            this.VendorEvents = new HashSet<VendorEvent>();
        }
    
        public int ID { get; set; }
        public string EventName { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> EventOrganiserID { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public string StreetAddress { get; set; }
        public string Suburb { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string GoogleMapsLink { get; set; }
        public string GPSCoordinates { get; set; }
        public Nullable<int> AgeLimit { get; set; }
        public Nullable<System.DateTime> TicketCutoffDate { get; set; }
        public Nullable<int> EventCategoryID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<System.DateTime> DateTimeUpdated { get; set; }
        public Nullable<int> SubdomainID { get; set; }
        public Nullable<bool> HasSeatingPlan { get; set; }
        public string ImageURL { get; set; }
        public Nullable<bool> IsMultiDayEvent { get; set; }
        public Nullable<bool> IsCashless { get; set; }
        public string Report1 { get; set; }
        public string Report2 { get; set; }
        public Nullable<bool> LimitOneTicketPerUser { get; set; }
    
        public virtual EventCategory EventCategory { get; set; }
        public virtual EventOrganiser EventOrganiser { get; set; }
        public virtual Region Region { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<EventImage> EventImages { get; set; }
        public virtual ICollection<Incident> Incidents { get; set; }
        public virtual ICollection<Promotion> Promotions { get; set; }
        public virtual ICollection<Staff> Staffs { get; set; }
        public virtual ICollection<TicketClass> TicketClasses { get; set; }
        public virtual ICollection<VendorEvent> VendorEvents { get; set; }
    }
}
