//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiidWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventImage
    {
        public int ID { get; set; }
        public string ImageURL { get; set; }
        public string ImageAltText { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> DateTimeUpdated { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
