//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiidWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventOrganiser
    {
        public EventOrganiser()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public string ContactName { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string SecondaryContactName { get; set; }
        public string SecondaryContactTelephone { get; set; }
        public string SecondaryContactEmail { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string Bank { get; set; }
        public string BankAccountNumber { get; set; }
        public string BranchCode { get; set; }
        public string BankType { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string BankAccountHolder { get; set; }
        public string ProfilePicURL { get; set; }
        public string HandHeldLoginPassword { get; set; }
        public Nullable<System.DateTime> DateTimeUpdated { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
        public virtual Status Status { get; set; }
    }
}
