//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiidWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeConfiguration
    {
        public int ID { get; set; }
        public string TransactionType { get; set; }
        public string PaymentType { get; set; }
        public Nullable<decimal> MinimumCharge { get; set; }
        public Nullable<decimal> PercentageCharge { get; set; }
        public Nullable<decimal> FixedFee { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> subdomainID { get; set; }
    }
}
