//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiidWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> IncidentDateTime { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<System.DateTime> DateTimeUpdated { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Status Status { get; set; }
    }
}
