//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiidWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogShipper
    {
        public int ID { get; set; }
        public string TableName { get; set; }
        public Nullable<int> LastMaxID { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> DateTimeUpdated { get; set; }
    }
}
