//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiidWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyMoney
    {
        public int ID { get; set; }
        public int EndUserID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> TransactionTypeID { get; set; }
        public Nullable<decimal> RunningBalance { get; set; }
        public Nullable<System.DateTime> DateTimeUpdated { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public string EmailNotificationStatus { get; set; }
        public string Reference { get; set; }
        public string Note { get; set; }
        public string UniqueID { get; set; }
    
        public virtual EndUser EndUser { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}
