//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiidWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class NFCTag
    {
        public int ID { get; set; }
        public string TagNumber { get; set; }
        public Nullable<int> EndUserID { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string ActivationCode { get; set; }
        public Nullable<int> TagPin { get; set; }
        public Nullable<System.DateTime> DateTimeUpdated { get; set; }
    
        public virtual EndUser EndUser { get; set; }
        public virtual Status Status { get; set; }
    }
}
