//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiidWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentChild
    {
        public int ID { get; set; }
        public Nullable<int> ParentUserID { get; set; }
        public Nullable<int> ChildUserID { get; set; }
        public Nullable<System.DateTime> DateTimeUpdated { get; set; }
    
        public virtual EndUser EndUser { get; set; }
        public virtual EndUser EndUser1 { get; set; }
    }
}
