//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiidWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromoCodeGeneric
    {
        public int ID { get; set; }
        public string GenericCode { get; set; }
        public Nullable<int> TicketClassID { get; set; }
        public Nullable<System.DateTime> DateValidated { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
    }
}
