//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiidWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.BankTransactions = new HashSet<BankTransaction>();
            this.EndUsers = new HashSet<EndUser>();
            this.Events = new HashSet<Event>();
            this.EventOrganisers = new HashSet<EventOrganiser>();
            this.Incidents = new HashSet<Incident>();
            this.NewsFeeds = new HashSet<NewsFeed>();
            this.NewsFeedComments = new HashSet<NewsFeedComment>();
            this.NFCTags = new HashSet<NFCTag>();
            this.PrivateMessages = new HashSet<PrivateMessage>();
            this.Promotions = new HashSet<Promotion>();
            this.Staffs = new HashSet<Staff>();
            this.TicketClasses = new HashSet<TicketClass>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Context { get; set; }
        public Nullable<System.DateTime> DateTimeUpdated { get; set; }
    
        public virtual ICollection<BankTransaction> BankTransactions { get; set; }
        public virtual ICollection<EndUser> EndUsers { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<EventOrganiser> EventOrganisers { get; set; }
        public virtual ICollection<Incident> Incidents { get; set; }
        public virtual ICollection<NewsFeed> NewsFeeds { get; set; }
        public virtual ICollection<NewsFeedComment> NewsFeedComments { get; set; }
        public virtual ICollection<NFCTag> NFCTags { get; set; }
        public virtual ICollection<PrivateMessage> PrivateMessages { get; set; }
        public virtual ICollection<Promotion> Promotions { get; set; }
        public virtual ICollection<Staff> Staffs { get; set; }
        public virtual ICollection<TicketClass> TicketClasses { get; set; }
    }
}
