//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiidWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.TicketClassSeats = new HashSet<TicketClassSeat>();
        }
    
        public int ID { get; set; }
        public string TicketNumber { get; set; }
        public Nullable<int> EndUserID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<decimal> TicketPurchasePrice { get; set; }
        public Nullable<int> TicketClassID { get; set; }
        public Nullable<System.DateTime> DatetimePurchased { get; set; }
        public Nullable<System.DateTime> DatetimeReserved { get; set; }
        public Nullable<System.DateTime> DatetimeRedeemed { get; set; }
        public string Hash { get; set; }
        public Nullable<System.DateTime> DateTimeUpdated { get; set; }
        public string UniquePaymentID { get; set; }
        public Nullable<System.DateTime> DateRefundRequested { get; set; }
        public Nullable<System.DateTime> DateRefundPaidOut { get; set; }
    
        public virtual EndUser EndUser { get; set; }
        public virtual TicketClass TicketClass { get; set; }
        public virtual ICollection<TicketClassSeat> TicketClassSeats { get; set; }
    }
}
