//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiidWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketClassSeatRange
    {
        public TicketClassSeatRange()
        {
            this.TicketClassSeats = new HashSet<TicketClassSeat>();
        }
    
        public int ID { get; set; }
        public Nullable<int> TicketClassID { get; set; }
        public string RowNumber { get; set; }
        public Nullable<int> FromSeatNumber { get; set; }
        public Nullable<int> ToSeatNumber { get; set; }
    
        public virtual TicketClass TicketClass { get; set; }
        public virtual ICollection<TicketClassSeat> TicketClassSeats { get; set; }
    }
}
