//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiidWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketClass
    {
        public TicketClass()
        {
            this.Tickets = new HashSet<Ticket>();
            this.TicketClassSeatRanges = new HashSet<TicketClassSeatRange>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public Nullable<int> EventID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ImageURL { get; set; }
        public Nullable<System.DateTime> DateTimeUpdated { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> RunningQuantity { get; set; }
        public Nullable<int> MaxOnlineSaleQuantity { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<bool> BoxOffice { get; set; }
        public Nullable<bool> HasPromoCodes { get; set; }
        public Nullable<bool> IsOnline { get; set; }
        public Nullable<int> PersonCount { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual ICollection<TicketClassSeatRange> TicketClassSeatRanges { get; set; }
    }
}
