//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiidWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionType
    {
        public TransactionType()
        {
            this.MyMoneys = new HashSet<MyMoney>();
        }
    
        public int ID { get; set; }
        public string TranTypeCode { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateTimeUpdated { get; set; }
        public string DebitCredit { get; set; }
    
        public virtual ICollection<MyMoney> MyMoneys { get; set; }
    }
}
